sync_interval: 15

pta:
  pta_session: xxx
  problem_set_id: "xx"

gplt:
  output_dir: "./output/gplt"
  excel_path: "./templates/gplt.xlsx"
  sheet_name: "template"

  standard_1: 800
  standard_2: 400

xcpcio:
  output_dir: "./output/xcpcio"
  excel_path: "./templates/xcpc.xlsx"
  sheet_name: "template"
  contest_path: "school-contest/zzuli/18th"
  unfrozen_path: "unfrozen-randomId"
  config:
    contest_name: ""
    start_time: 1775440800000 # milliseconds
    end_time: 1775458800000 # milliseconds
    penalty: 1200 # seconds
    frozen_time: 3600 # seconds
    problem_id: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]
    balloon_color:
      - color: "#000000"
        background_color: "#e25b2e"
      - color: "#000000"
        background_color: "#f8b7bd"
      - color: "#000000"
        background_color: "#14247c"
      - color: "#000000"
        background_color: "#203c30"
      - color: "#000000"
        background_color: "#4aa0dd"
      - color: "#000000"
        background_color: "#0f9493"
      - color: "#000000"
        background_color: "#0d9646"
      - color: "#000000"
        background_color: "#ffffff"
      - color: "#000000"
        background_color: "#fc63a3"
      - color: "#000000"
        background_color: "#ff0000"
      - color: "#000000"
        background_color: "#ffff00"
      - color: "#000000"
        background_color: "#6b48a6"
    options:
      enable_organization: true
      submission_timestamp_unit: "millisecond"
    organizations:
      url: "organizations.json"
    logo:
      preset: "ZZULI"
    status_time_display:
      correct: true
      incorrect: true
      pending: true
    group:
      official: "校内队伍"
      unofficial: "校外队伍"
    medal:
      official:
        gold: 5
        silver: 8
        bronze: 12
      unofficial:
        gold: 10
