sync_interval: 15

pta:
  pta_session: xxx
  problem_set_id: "xx"

gplt:
  output_dir: "./output/gplt"
  excel_path: "./xlsx/gplt.xlsx"
  sheet_name: "template"

  standard_1: 800
  standard_2: 400

xcpcio:
  output_dir: "./output/xcpcio"
  excel_path: "./xlsx/xcpc.xlsx"
  sheet_name: "template"

  contest_path: "school-contest/zzuli/school-based/18th"
  frozen_diff: 3600
